name: IdracFanControl Docker Build and Push to GHCR

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/idrac-fan-control:latest .

    # Step 4: Push the Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/idrac-fan-control:latest
